// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRate: typeof import('element-plus/es')['ElRate']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconButton: typeof import('./src/components/button/IconButton.vue')['default']
    LevelStack: typeof import('./src/components/stack/LevelStack.vue')['default']
    LoadingIcon: typeof import('./src/components/icon/LoadingIcon.vue')['default']
    LogTerminal: typeof import('./src/components/terminal/LogTerminal.vue')['default']
    MacOSController: typeof import('./src/components/customize/controller/MacOSController.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    NavBarInner: typeof import('./src/components/layout/NavBarInner.vue')['default']
    PluginIcon: typeof import('./src/components/plugin/PluginIcon.vue')['default']
    PluginInfo: typeof import('./src/components/plugin/PluginInfo.vue')['default']
    PluginItem: typeof import('./src/components/plugin/PluginItem.vue')['default']
    RemixIcon: typeof import('./src/components/icon/RemixIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TBlockLine: typeof import('./src/components/group/TBlockLine.vue')['default']
    TBlockSelect: typeof import('./src/components/select/TBlockSelect.vue')['default']
    TBlockSwitch: typeof import('./src/components/switch/TBlockSwitch.vue')['default']
    TDialogMention: typeof import('./src/components/dialog/TDialogMention.vue')['default']
    TGroupBlock: typeof import('./src/components/group/TGroupBlock.vue')['default']
    TSelect: typeof import('./src/components/select/TSelect.vue')['default']
    TSelectItem: typeof import('./src/components/select/TSelectItem.vue')['default']
    TSwitch: typeof import('./src/components/switch/TSwitch.vue')['default']
    TTabHeader: typeof import('./src/components/tabs/TTabHeader.vue')['default']
    TTabItem: typeof import('./src/components/tabs/TTabItem.vue')['default']
    TTabItemGroup: typeof import('./src/components/tabs/TTabItemGroup.vue')['default']
    TTabs: typeof import('./src/components/tabs/TTabs.vue')['default']
    TvTabItem: typeof import('./src/components/tabs/vertical/TvTabItem.vue')['default']
    TvTabItemGroup: typeof import('./src/components/tabs/vertical/TvTabItemGroup.vue')['default']
    TvTabs: typeof import('./src/components/tabs/vertical/TvTabs.vue')['default']
    WindowsController: typeof import('./src/components/customize/controller/WindowsController.vue')['default']
  }
}
